export const NuxtLogo = () => import('../../components/NuxtLogo.vue' /* webpackChunkName: "components/nuxt-logo" */).then(c => wrapFunctional(c.default || c))
export const AuthenticationLogin2 = () => import('../../components/Authentication/login-2.vue' /* webpackChunkName: "components/authentication-login2" */).then(c => wrapFunctional(c.default || c))
export const AuthenticationLogin = () => import('../../components/Authentication/login.vue' /* webpackChunkName: "components/authentication-login" */).then(c => wrapFunctional(c.default || c))
export const AuthenticationSignup2 = () => import('../../components/Authentication/signup-2.vue' /* webpackChunkName: "components/authentication-signup2" */).then(c => wrapFunctional(c.default || c))
export const AuthenticationSignup = () => import('../../components/Authentication/signup.vue' /* webpackChunkName: "components/authentication-signup" */).then(c => wrapFunctional(c.default || c))
export const BlogsDetails = () => import('../../components/blogs/details.vue' /* webpackChunkName: "components/blogs-details" */).then(c => wrapFunctional(c.default || c))
export const BlogsLeftSidebar = () => import('../../components/blogs/left-sidebar.vue' /* webpackChunkName: "components/blogs-left-sidebar" */).then(c => wrapFunctional(c.default || c))
export const BlogsNoSidebar = () => import('../../components/blogs/no-sidebar.vue' /* webpackChunkName: "components/blogs-no-sidebar" */).then(c => wrapFunctional(c.default || c))
export const BlogsRightSidebar = () => import('../../components/blogs/right-sidebar.vue' /* webpackChunkName: "components/blogs-right-sidebar" */).then(c => wrapFunctional(c.default || c))
export const LandingPageAppDesign = () => import('../../components/landing-page/app-design.vue' /* webpackChunkName: "components/landing-page-app-design" */).then(c => wrapFunctional(c.default || c))
export const LandingPageChitChat = () => import('../../components/landing-page/chit-chat.vue' /* webpackChunkName: "components/landing-page-chit-chat" */).then(c => wrapFunctional(c.default || c))
export const LandingPageCollaboration = () => import('../../components/landing-page/collaboration.vue' /* webpackChunkName: "components/landing-page-collaboration" */).then(c => wrapFunctional(c.default || c))
export const LandingPage = () => import('../../components/landing-page/index.vue' /* webpackChunkName: "components/landing-page" */).then(c => wrapFunctional(c.default || c))
export const LandingPageOfficial = () => import('../../components/landing-page/official.vue' /* webpackChunkName: "components/landing-page-official" */).then(c => wrapFunctional(c.default || c))
export const LandingPagePricingPlan = () => import('../../components/landing-page/pricing-plan.vue' /* webpackChunkName: "components/landing-page-pricing-plan" */).then(c => wrapFunctional(c.default || c))
export const LandingPageSecureApp = () => import('../../components/landing-page/secure-app.vue' /* webpackChunkName: "components/landing-page-secure-app" */).then(c => wrapFunctional(c.default || c))
export const LandingPageSlider = () => import('../../components/landing-page/slider.vue' /* webpackChunkName: "components/landing-page-slider" */).then(c => wrapFunctional(c.default || c))
export const LandingPageSubscribeUpdate = () => import('../../components/landing-page/subscribe-update.vue' /* webpackChunkName: "components/landing-page-subscribe-update" */).then(c => wrapFunctional(c.default || c))
export const LandingPageTeamWork = () => import('../../components/landing-page/team-work.vue' /* webpackChunkName: "components/landing-page-team-work" */).then(c => wrapFunctional(c.default || c))
export const LandingPageTestimonial = () => import('../../components/landing-page/testimonial.vue' /* webpackChunkName: "components/landing-page-testimonial" */).then(c => wrapFunctional(c.default || c))
export const MessengerChat = () => import('../../components/messenger/chat.vue' /* webpackChunkName: "components/messenger-chat" */).then(c => wrapFunctional(c.default || c))
export const Messenger = () => import('../../components/messenger/index.vue' /* webpackChunkName: "components/messenger" */).then(c => wrapFunctional(c.default || c))
export const MessengerLeftSidebar = () => import('../../components/messenger/left-sidebar.vue' /* webpackChunkName: "components/messenger-left-sidebar" */).then(c => wrapFunctional(c.default || c))
export const MessengerNav = () => import('../../components/messenger/nav.vue' /* webpackChunkName: "components/messenger-nav" */).then(c => wrapFunctional(c.default || c))
export const MessengerStickers = () => import('../../components/messenger/stickers.vue' /* webpackChunkName: "components/messenger-stickers" */).then(c => wrapFunctional(c.default || c))
export const PagenotfoundErrorpage = () => import('../../components/pagenotfound/errorpage.vue' /* webpackChunkName: "components/pagenotfound-errorpage" */).then(c => wrapFunctional(c.default || c))
export const Pagenotfound = () => import('../../components/pagenotfound/index.vue' /* webpackChunkName: "components/pagenotfound" */).then(c => wrapFunctional(c.default || c))
export const BlogsCommonBlogFollowUs = () => import('../../components/blogs/Common/blog_follow_us.vue' /* webpackChunkName: "components/blogs-common-blog-follow-us" */).then(c => wrapFunctional(c.default || c))
export const BlogsCommonBlogHeader = () => import('../../components/blogs/Common/blog_header.vue' /* webpackChunkName: "components/blogs-common-blog-header" */).then(c => wrapFunctional(c.default || c))
export const BlogsCommonBlogMedia = () => import('../../components/blogs/Common/blog_media.vue' /* webpackChunkName: "components/blogs-common-blog-media" */).then(c => wrapFunctional(c.default || c))
export const BlogsCommonBlogPopular = () => import('../../components/blogs/Common/blog_popular.vue' /* webpackChunkName: "components/blogs-common-blog-popular" */).then(c => wrapFunctional(c.default || c))
export const BlogsCommonBlogRecent = () => import('../../components/blogs/Common/blog_recent.vue' /* webpackChunkName: "components/blogs-common-blog-recent" */).then(c => wrapFunctional(c.default || c))
export const BlogsCommonBlogSearch = () => import('../../components/blogs/Common/blog_search.vue' /* webpackChunkName: "components/blogs-common-blog-search" */).then(c => wrapFunctional(c.default || c))
export const BlogsCommonBlogTags = () => import('../../components/blogs/Common/blog_tags.vue' /* webpackChunkName: "components/blogs-common-blog-tags" */).then(c => wrapFunctional(c.default || c))
export const BlogsBlogCard = () => import('../../components/blogs/blog_card/blog_card.vue' /* webpackChunkName: "components/blogs-blog-card" */).then(c => wrapFunctional(c.default || c))
export const BlogsBlogSidebar = () => import('../../components/blogs/blog_sidebar/blog_sidebar.vue' /* webpackChunkName: "components/blogs-blog-sidebar" */).then(c => wrapFunctional(c.default || c))
export const BlogsBlogNoSidebar = () => import('../../components/blogs/blog_no-sidebar/blog_no-sidebar.vue' /* webpackChunkName: "components/blogs-blog-no-sidebar" */).then(c => wrapFunctional(c.default || c))
export const BlogsBlogDetail = () => import('../../components/blogs/blog_details/blog_detail.vue' /* webpackChunkName: "components/blogs-blog-detail" */).then(c => wrapFunctional(c.default || c))
export const BlogsComments = () => import('../../components/blogs/comments/comments.vue' /* webpackChunkName: "components/blogs-comments" */).then(c => wrapFunctional(c.default || c))
export const BlogsLeaveComments = () => import('../../components/blogs/leave_coments/leave_comments.vue' /* webpackChunkName: "components/blogs-leave-comments" */).then(c => wrapFunctional(c.default || c))
export const CommonBreadcrumbBreadCrumbs = () => import('../../components/common/breadcrumb/bread_crumbs.vue' /* webpackChunkName: "components/common-breadcrumb-bread-crumbs" */).then(c => wrapFunctional(c.default || c))
export const CommonFooter = () => import('../../components/common/footer/footer.vue' /* webpackChunkName: "components/common-footer" */).then(c => wrapFunctional(c.default || c))
export const CommonNavbar = () => import('../../components/common/navbar/navbar.vue' /* webpackChunkName: "components/common-navbar" */).then(c => wrapFunctional(c.default || c))
export const CommonHeader = () => import('../../components/common/header/header.vue' /* webpackChunkName: "components/common-header" */).then(c => wrapFunctional(c.default || c))
export const CommonLogo = () => import('../../components/common/logo/logo.vue' /* webpackChunkName: "components/common-logo" */).then(c => wrapFunctional(c.default || c))
export const CommonTapToTopTaptop = () => import('../../components/common/tap-to-top/taptop.vue' /* webpackChunkName: "components/common-tap-to-top-taptop" */).then(c => wrapFunctional(c.default || c))
export const BonusPageAboutPage = () => import('../../components/bonus_page/about/about-page.vue' /* webpackChunkName: "components/bonus-page-about-page" */).then(c => wrapFunctional(c.default || c))
export const BonusPageAboutCounter = () => import('../../components/bonus_page/about/counter.vue' /* webpackChunkName: "components/bonus-page-about-counter" */).then(c => wrapFunctional(c.default || c))
export const BonusPageAbout = () => import('../../components/bonus_page/about/index.vue' /* webpackChunkName: "components/bonus-page-about" */).then(c => wrapFunctional(c.default || c))
export const BonusPageFaq = () => import('../../components/bonus_page/faq/index.vue' /* webpackChunkName: "components/bonus-page-faq" */).then(c => wrapFunctional(c.default || c))
export const BonusPagePriceBonusprice = () => import('../../components/bonus_page/price/bonusprice.vue' /* webpackChunkName: "components/bonus-page-price-bonusprice" */).then(c => wrapFunctional(c.default || c))
export const BonusPagePrice = () => import('../../components/bonus_page/price/index.vue' /* webpackChunkName: "components/bonus-page-price" */).then(c => wrapFunctional(c.default || c))
export const MessengerCallsAllcalls = () => import('../../components/messenger/calls/allcalls.vue' /* webpackChunkName: "components/messenger-calls-allcalls" */).then(c => wrapFunctional(c.default || c))
export const MessengerCallsCallcontent = () => import('../../components/messenger/calls/callcontent.vue' /* webpackChunkName: "components/messenger-calls-callcontent" */).then(c => wrapFunctional(c.default || c))
export const MessengerCallsDial = () => import('../../components/messenger/calls/dial.vue' /* webpackChunkName: "components/messenger-calls-dial" */).then(c => wrapFunctional(c.default || c))
export const MessengerCalls = () => import('../../components/messenger/calls/index.vue' /* webpackChunkName: "components/messenger-calls" */).then(c => wrapFunctional(c.default || c))
export const MessengerCallsMissed = () => import('../../components/messenger/calls/missed.vue' /* webpackChunkName: "components/messenger-calls-missed" */).then(c => wrapFunctional(c.default || c))
export const MessengerCallsReceived = () => import('../../components/messenger/calls/received.vue' /* webpackChunkName: "components/messenger-calls-received" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsBackgroundcolor = () => import('../../components/bonus_page/elements/backgroundcolor.vue' /* webpackChunkName: "components/bonus-page-elements-backgroundcolor" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsBadge = () => import('../../components/bonus_page/elements/badge.vue' /* webpackChunkName: "components/bonus-page-elements-badge" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsBadgeWithIcons = () => import('../../components/bonus_page/elements/badgeWithIcons.vue' /* webpackChunkName: "components/bonus-page-elements-badge-with-icons" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsBadgeWithSmallLabelIcon = () => import('../../components/bonus_page/elements/badgeWithSmallLabelIcon.vue' /* webpackChunkName: "components/bonus-page-elements-badge-with-small-label-icon" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsBadgeWithTypography = () => import('../../components/bonus_page/elements/badgeWithTypography.vue' /* webpackChunkName: "components/bonus-page-elements-badge-with-typography" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsBadgeWithstatus = () => import('../../components/bonus_page/elements/badgeWithstatus.vue' /* webpackChunkName: "components/bonus-page-elements-badge-withstatus" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsButtonbackground = () => import('../../components/bonus_page/elements/buttonbackground.vue' /* webpackChunkName: "components/bonus-page-elements-buttonbackground" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsButtons = () => import('../../components/bonus_page/elements/buttons.vue' /* webpackChunkName: "components/bonus-page-elements-buttons" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsFonts = () => import('../../components/bonus_page/elements/fonts.vue' /* webpackChunkName: "components/bonus-page-elements-fonts" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsIcons = () => import('../../components/bonus_page/elements/icons.vue' /* webpackChunkName: "components/bonus-page-elements-icons" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsImages = () => import('../../components/bonus_page/elements/images.vue' /* webpackChunkName: "components/bonus-page-elements-images" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElements = () => import('../../components/bonus_page/elements/index.vue' /* webpackChunkName: "components/bonus-page-elements" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsLabelFonts = () => import('../../components/bonus_page/elements/label-fonts.vue' /* webpackChunkName: "components/bonus-page-elements-label-fonts" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsMainChat = () => import('../../components/bonus_page/elements/mainChat.vue' /* webpackChunkName: "components/bonus-page-elements-main-chat" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsMessageBox = () => import('../../components/bonus_page/elements/messageBox.vue' /* webpackChunkName: "components/bonus-page-elements-message-box" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsPhoneButton = () => import('../../components/bonus_page/elements/phoneButton.vue' /* webpackChunkName: "components/bonus-page-elements-phone-button" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsSharedDoc = () => import('../../components/bonus_page/elements/sharedDoc.vue' /* webpackChunkName: "components/bonus-page-elements-shared-doc" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsSpanParag = () => import('../../components/bonus_page/elements/span-parag.vue' /* webpackChunkName: "components/bonus-page-elements-span-parag" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsThemebuttons = () => import('../../components/bonus_page/elements/themebuttons.vue' /* webpackChunkName: "components/bonus-page-elements-themebuttons" */).then(c => wrapFunctional(c.default || c))
export const BonusPageElementsTypography = () => import('../../components/bonus_page/elements/typography.vue' /* webpackChunkName: "components/bonus-page-elements-typography" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsContactcontent = () => import('../../components/messenger/contacts/contactcontent.vue' /* webpackChunkName: "components/messenger-contacts-contactcontent" */).then(c => wrapFunctional(c.default || c))
export const MessengerContacts = () => import('../../components/messenger/contacts/contacts.vue' /* webpackChunkName: "components/messenger-contacts" */).then(c => wrapFunctional(c.default || c))
export const MessengerCustomizerChatwallpaper = () => import('../../components/messenger/customizer/chatwallpaper.vue' /* webpackChunkName: "components/messenger-customizer-chatwallpaper" */).then(c => wrapFunctional(c.default || c))
export const MessengerCustomizerChoosecolor = () => import('../../components/messenger/customizer/choosecolor.vue' /* webpackChunkName: "components/messenger-customizer-choosecolor" */).then(c => wrapFunctional(c.default || c))
export const MessengerCustomizerCustomizesetting = () => import('../../components/messenger/customizer/customizesetting.vue' /* webpackChunkName: "components/messenger-customizer-customizesetting" */).then(c => wrapFunctional(c.default || c))
export const MessengerCustomizer = () => import('../../components/messenger/customizer/index.vue' /* webpackChunkName: "components/messenger-customizer" */).then(c => wrapFunctional(c.default || c))
export const MessengerCustomizerLayout = () => import('../../components/messenger/customizer/layout.vue' /* webpackChunkName: "components/messenger-customizer-layout" */).then(c => wrapFunctional(c.default || c))
export const MessengerCustomizerSidebar = () => import('../../components/messenger/customizer/sidebar.vue' /* webpackChunkName: "components/messenger-customizer-sidebar" */).then(c => wrapFunctional(c.default || c))
export const MessengerCommonDocumentslist = () => import('../../components/messenger/common/documentslist.vue' /* webpackChunkName: "components/messenger-common-documentslist" */).then(c => wrapFunctional(c.default || c))
export const MessengerCommonDropdown = () => import('../../components/messenger/common/dropdown.vue' /* webpackChunkName: "components/messenger-common-dropdown" */).then(c => wrapFunctional(c.default || c))
export const MessengerCommonProfile = () => import('../../components/messenger/common/profile.vue' /* webpackChunkName: "components/messenger-common-profile" */).then(c => wrapFunctional(c.default || c))
export const MessengerCommonShareddoc = () => import('../../components/messenger/common/shareddoc.vue' /* webpackChunkName: "components/messenger-common-shareddoc" */).then(c => wrapFunctional(c.default || c))
export const MessengerCommonUserdropdown = () => import('../../components/messenger/common/userdropdown.vue' /* webpackChunkName: "components/messenger-common-userdropdown" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarChats = () => import('../../components/messenger/lefsidebar/chats.vue' /* webpackChunkName: "components/messenger-lefsidebar-chats" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarContactList = () => import('../../components/messenger/lefsidebar/contact_list.vue' /* webpackChunkName: "components/messenger-lefsidebar-contact-list" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarContacts = () => import('../../components/messenger/lefsidebar/contacts.vue' /* webpackChunkName: "components/messenger-lefsidebar-contacts" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarDocument = () => import('../../components/messenger/lefsidebar/document.vue' /* webpackChunkName: "components/messenger-lefsidebar-document" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarNotification = () => import('../../components/messenger/lefsidebar/notification.vue' /* webpackChunkName: "components/messenger-lefsidebar-notification" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarSettings = () => import('../../components/messenger/lefsidebar/settings.vue' /* webpackChunkName: "components/messenger-lefsidebar-settings" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarStatus = () => import('../../components/messenger/lefsidebar/status.vue' /* webpackChunkName: "components/messenger-lefsidebar-status" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsAudiocall1 = () => import('../../components/messenger/modals/audiocall1.vue' /* webpackChunkName: "components/messenger-modals-audiocall1" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsAudiocall2 = () => import('../../components/messenger/modals/audiocall2.vue' /* webpackChunkName: "components/messenger-modals-audiocall2" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsCodesnippets = () => import('../../components/messenger/modals/codesnippets.vue' /* webpackChunkName: "components/messenger-modals-codesnippets" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsCreatetodo = () => import('../../components/messenger/modals/createtodo.vue' /* webpackChunkName: "components/messenger-modals-createtodo" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsGroupaudiocall = () => import('../../components/messenger/modals/groupaudiocall.vue' /* webpackChunkName: "components/messenger-modals-groupaudiocall" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsGroupvediocall = () => import('../../components/messenger/modals/groupvediocall.vue' /* webpackChunkName: "components/messenger-modals-groupvediocall" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsNewCall = () => import('../../components/messenger/modals/newCall.vue' /* webpackChunkName: "components/messenger-modals-new-call" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsNewChat = () => import('../../components/messenger/modals/newChat.vue' /* webpackChunkName: "components/messenger-modals-new-chat" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsNewContact = () => import('../../components/messenger/modals/newContact.vue' /* webpackChunkName: "components/messenger-modals-new-contact" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsNotesmodal = () => import('../../components/messenger/modals/notesmodal.vue' /* webpackChunkName: "components/messenger-modals-notesmodal" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsPollModal = () => import('../../components/messenger/modals/pollModal.vue' /* webpackChunkName: "components/messenger-modals-poll-modal" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsSetreminder = () => import('../../components/messenger/modals/setreminder.vue' /* webpackChunkName: "components/messenger-modals-setreminder" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsTodo = () => import('../../components/messenger/modals/todo.vue' /* webpackChunkName: "components/messenger-modals-todo" */).then(c => wrapFunctional(c.default || c))
export const MessengerModalsVediocall = () => import('../../components/messenger/modals/vediocall.vue' /* webpackChunkName: "components/messenger-modals-vediocall" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebar = () => import('../../components/messenger/rightsidebar/index.vue' /* webpackChunkName: "components/messenger-rightsidebar" */).then(c => wrapFunctional(c.default || c))
export const MessengerChatDirectChatDirectchatheader = () => import('../../components/messenger/chat/DirectChat/directchatheader.vue' /* webpackChunkName: "components/messenger-chat-direct-chat-directchatheader" */).then(c => wrapFunctional(c.default || c))
export const MessengerChatDirectChatDirectchatuser = () => import('../../components/messenger/chat/DirectChat/directchatuser.vue' /* webpackChunkName: "components/messenger-chat-direct-chat-directchatuser" */).then(c => wrapFunctional(c.default || c))
export const MessengerChatDirectChatDirectcustomchat = () => import('../../components/messenger/chat/DirectChat/directcustomchat.vue' /* webpackChunkName: "components/messenger-chat-direct-chat-directcustomchat" */).then(c => wrapFunctional(c.default || c))
export const MessengerChatGroupChatGroupchatheader = () => import('../../components/messenger/chat/GroupChat/groupchatheader.vue' /* webpackChunkName: "components/messenger-chat-group-chat-groupchatheader" */).then(c => wrapFunctional(c.default || c))
export const MessengerChatGroupChatGroupchatuser = () => import('../../components/messenger/chat/GroupChat/groupchatuser.vue' /* webpackChunkName: "components/messenger-chat-group-chat-groupchatuser" */).then(c => wrapFunctional(c.default || c))
export const MessengerChatGroupChatGroupcustomchat = () => import('../../components/messenger/chat/GroupChat/groupcustomchat.vue' /* webpackChunkName: "components/messenger-chat-group-chat-groupcustomchat" */).then(c => wrapFunctional(c.default || c))
export const MessengerChatOfficialChatOfficialchatheader = () => import('../../components/messenger/chat/OfficialChat/officialchatheader.vue' /* webpackChunkName: "components/messenger-chat-official-chat-officialchatheader" */).then(c => wrapFunctional(c.default || c))
export const MessengerChatOfficialChatOfficialchatuser = () => import('../../components/messenger/chat/OfficialChat/officialchatuser.vue' /* webpackChunkName: "components/messenger-chat-official-chat-officialchatuser" */).then(c => wrapFunctional(c.default || c))
export const MessengerChatOfficialChatOfficialcustomchat = () => import('../../components/messenger/chat/OfficialChat/officialcustomchat.vue' /* webpackChunkName: "components/messenger-chat-official-chat-officialcustomchat" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsFriendContactFriendcontactchat = () => import('../../components/messenger/contacts/FriendContact/friendcontactchat.vue' /* webpackChunkName: "components/messenger-contacts-friend-contact-friendcontactchat" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsFriendContactFriendcontactheader = () => import('../../components/messenger/contacts/FriendContact/friendcontactheader.vue' /* webpackChunkName: "components/messenger-contacts-friend-contact-friendcontactheader" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsFriendContactFriendcontactuser = () => import('../../components/messenger/contacts/FriendContact/friendcontactuser.vue' /* webpackChunkName: "components/messenger-contacts-friend-contact-friendcontactuser" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsGroupContactGroupcontactchat = () => import('../../components/messenger/contacts/GroupContact/groupcontactchat.vue' /* webpackChunkName: "components/messenger-contacts-group-contact-groupcontactchat" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsGroupContactGroupcontactheader = () => import('../../components/messenger/contacts/GroupContact/groupcontactheader.vue' /* webpackChunkName: "components/messenger-contacts-group-contact-groupcontactheader" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsGroupContactGroupcontactuser = () => import('../../components/messenger/contacts/GroupContact/groupcontactuser.vue' /* webpackChunkName: "components/messenger-contacts-group-contact-groupcontactuser" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsOfficialContactOfficialcontactchat = () => import('../../components/messenger/contacts/OfficialContact/officialcontactchat.vue' /* webpackChunkName: "components/messenger-contacts-official-contact-officialcontactchat" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsOfficialContactOfficialcontactheader = () => import('../../components/messenger/contacts/OfficialContact/officialcontactheader.vue' /* webpackChunkName: "components/messenger-contacts-official-contact-officialcontactheader" */).then(c => wrapFunctional(c.default || c))
export const MessengerContactsOfficialContactOfficialcontactuser = () => import('../../components/messenger/contacts/OfficialContact/officialcontactuser.vue' /* webpackChunkName: "components/messenger-contacts-official-contact-officialcontactuser" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarSettingAccount = () => import('../../components/messenger/lefsidebar/setting/account.vue' /* webpackChunkName: "components/messenger-lefsidebar-setting-account" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarSettingChat = () => import('../../components/messenger/lefsidebar/setting/chat.vue' /* webpackChunkName: "components/messenger-lefsidebar-setting-chat" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarSettingHelp = () => import('../../components/messenger/lefsidebar/setting/help.vue' /* webpackChunkName: "components/messenger-lefsidebar-setting-help" */).then(c => wrapFunctional(c.default || c))
export const MessengerLefsidebarSettingIntegratin = () => import('../../components/messenger/lefsidebar/setting/integratin.vue' /* webpackChunkName: "components/messenger-lefsidebar-setting-integratin" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarFiles = () => import('../../components/messenger/rightsidebar/files/index.vue' /* webpackChunkName: "components/messenger-rightsidebar-files" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarFilesLink = () => import('../../components/messenger/rightsidebar/files/link.vue' /* webpackChunkName: "components/messenger-rightsidebar-files-link" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarFilesMedia = () => import('../../components/messenger/rightsidebar/files/media.vue' /* webpackChunkName: "components/messenger-rightsidebar-files-media" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarReminder = () => import('../../components/messenger/rightsidebar/reminder/index.vue' /* webpackChunkName: "components/messenger-rightsidebar-reminder" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarNotes = () => import('../../components/messenger/rightsidebar/notes/index.vue' /* webpackChunkName: "components/messenger-rightsidebar-notes" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarTodo = () => import('../../components/messenger/rightsidebar/todo/index.vue' /* webpackChunkName: "components/messenger-rightsidebar-todo" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarProfileCommongroup = () => import('../../components/messenger/rightsidebar/profile/commongroup.vue' /* webpackChunkName: "components/messenger-rightsidebar-profile-commongroup" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarProfileContactinfo = () => import('../../components/messenger/rightsidebar/profile/contactinfo.vue' /* webpackChunkName: "components/messenger-rightsidebar-profile-contactinfo" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarProfile = () => import('../../components/messenger/rightsidebar/profile/index.vue' /* webpackChunkName: "components/messenger-rightsidebar-profile" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarProfilePersonalinfo = () => import('../../components/messenger/rightsidebar/profile/personalinfo.vue' /* webpackChunkName: "components/messenger-rightsidebar-profile-personalinfo" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarProfileSharedmedia = () => import('../../components/messenger/rightsidebar/profile/sharedmedia.vue' /* webpackChunkName: "components/messenger-rightsidebar-profile-sharedmedia" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarProfileStarredmessages = () => import('../../components/messenger/rightsidebar/profile/starredmessages.vue' /* webpackChunkName: "components/messenger-rightsidebar-profile-starredmessages" */).then(c => wrapFunctional(c.default || c))
export const MessengerRightsidebarProfileStatus = () => import('../../components/messenger/rightsidebar/profile/status.vue' /* webpackChunkName: "components/messenger-rightsidebar-profile-status" */).then(c => wrapFunctional(c.default || c))

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
